//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliente.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.wsUsuarioSoap")]
    public interface wsUsuarioSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Usuario del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Loguear", ReplyAction="*")]
        Cliente.ServiceReference1.LoguearResponse Loguear(Cliente.ServiceReference1.LoguearRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Loguear", ReplyAction="*")]
        System.Threading.Tasks.Task<Cliente.ServiceReference1.LoguearResponse> LoguearAsync(Cliente.ServiceReference1.LoguearRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoguearRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Loguear", Namespace="http://tempuri.org/", Order=0)]
        public Cliente.ServiceReference1.LoguearRequestBody Body;
        
        public LoguearRequest() {
        }
        
        public LoguearRequest(Cliente.ServiceReference1.LoguearRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoguearRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Contrasena;
        
        public LoguearRequestBody() {
        }
        
        public LoguearRequestBody(string Usuario, string Contrasena) {
            this.Usuario = Usuario;
            this.Contrasena = Contrasena;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoguearResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoguearResponse", Namespace="http://tempuri.org/", Order=0)]
        public Cliente.ServiceReference1.LoguearResponseBody Body;
        
        public LoguearResponse() {
        }
        
        public LoguearResponse(Cliente.ServiceReference1.LoguearResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoguearResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Cliente.ServiceReference1.ArrayOfString LoguearResult;
        
        public LoguearResponseBody() {
        }
        
        public LoguearResponseBody(Cliente.ServiceReference1.ArrayOfString LoguearResult) {
            this.LoguearResult = LoguearResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsUsuarioSoapChannel : Cliente.ServiceReference1.wsUsuarioSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsUsuarioSoapClient : System.ServiceModel.ClientBase<Cliente.ServiceReference1.wsUsuarioSoap>, Cliente.ServiceReference1.wsUsuarioSoap {
        
        public wsUsuarioSoapClient() {
        }
        
        public wsUsuarioSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsUsuarioSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsUsuarioSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsUsuarioSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Cliente.ServiceReference1.LoguearResponse Cliente.ServiceReference1.wsUsuarioSoap.Loguear(Cliente.ServiceReference1.LoguearRequest request) {
            return base.Channel.Loguear(request);
        }
        
        public Cliente.ServiceReference1.ArrayOfString Loguear(string Usuario, string Contrasena) {
            Cliente.ServiceReference1.LoguearRequest inValue = new Cliente.ServiceReference1.LoguearRequest();
            inValue.Body = new Cliente.ServiceReference1.LoguearRequestBody();
            inValue.Body.Usuario = Usuario;
            inValue.Body.Contrasena = Contrasena;
            Cliente.ServiceReference1.LoguearResponse retVal = ((Cliente.ServiceReference1.wsUsuarioSoap)(this)).Loguear(inValue);
            return retVal.Body.LoguearResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Cliente.ServiceReference1.LoguearResponse> Cliente.ServiceReference1.wsUsuarioSoap.LoguearAsync(Cliente.ServiceReference1.LoguearRequest request) {
            return base.Channel.LoguearAsync(request);
        }
        
        public System.Threading.Tasks.Task<Cliente.ServiceReference1.LoguearResponse> LoguearAsync(string Usuario, string Contrasena) {
            Cliente.ServiceReference1.LoguearRequest inValue = new Cliente.ServiceReference1.LoguearRequest();
            inValue.Body = new Cliente.ServiceReference1.LoguearRequestBody();
            inValue.Body.Usuario = Usuario;
            inValue.Body.Contrasena = Contrasena;
            return ((Cliente.ServiceReference1.wsUsuarioSoap)(this)).LoguearAsync(inValue);
        }
    }
}
